import React from 'react'

const Terms = () => {
  return (
    <>
        <label htmlFor="my-modal-6" className="btn modal-button btn-sm">Terms & Conditions</label>

        <input type="checkbox" id="my-modal-6" className="modal-toggle" />
        <div className="modal modal-bottom sm:modal-middle">
        <div className="modal-box">
            <h3 className="text-2xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r capitalize from-red-300 to-sky-500 leading-snug mb-2">Terms & Conditions</h3>
            <p className="py-4">Urban Uprise Crew is a collection of digital artworks (NFTs) running on the Polygon network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Polygon wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the Urban Uprise Crew smart contract runs on the Polygon network, there is no ability to undo, reverse, or restore any transactions.</p>
            <p className="py-4">This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving Urban Uprise Crew digital collectibles.</p>
            <h3 className="text-2xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r capitalize from-red-300 to-sky-500 leading-snug mb-2">Ownership</h3>
            <p className="py-4">i. You OWN the NFT. Each UUC is an NFT on the Polygon blockchain. When you purchase an NFT, you own the underlying UUC, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Polygon Network: at no point may we seize, freeze, or otherwise modify the ownership of any UUC.</p>
            <p className='py-4'>ii. Personal Use. Subject to your continued compliance with these Terms, Creative Organization DAO LLC grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely for the following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your UUC / NFT, provided that the marketplace cryptographically verifies each UUC owner’s rights to display the Art for their UUC to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your UUC, provided that the website/application cryptographically verifies each UUC owner’s rights to display the Art for their UUC to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the UUC leaves the website/application.</p>
            <p className='py-4'>iii. Commercial Use. Subject to your continued compliance with these Terms, Creative Organization DAO LLC grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of UUCs generally, provided that the marketplace cryptographically verifies eachUUC owner’s rights to display the Art for their UUC to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of UUCs generally, provided that the third party website or application cryptographically verifies each UUC owner’s rights to display the Art for theirUUC to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased UUC leaves the website/application; or (iii) earning revenue from any of the foregoing.</p>
            <div className="modal-action">
            <label htmlFor="my-modal-6" className="btn">CLOSE</label>
            </div>
        </div>
        </div>
    </>
  )
}

export default Terms;